DROP TABLE IF EXISTS chars;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE chars (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);